version: '3.1'

networks:
  dockerapi-dev:
    driver: bridge 

services:

  postgres_image:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "Namsdb"
    networks:
      - dockerapi-dev

  newspaperadvertisementmanagementsystem:
    image: anudeepgunukula/newspaperadvertisementmanagementsystem
    depends_on:
       - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
          DBServer: "postgres_image"
    ports:
      - "5000:80"
    networks:
      - dockerapi-dev  

  angular:
    image: anudeepgunukula/namsui
    ports:
      - "80:4200"
    networks:
      - dockerapi-dev