// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewspaperAdvertisementManagementSystem.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NewspaperAdvertisementManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220107062138_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NewspaperAdvertisementManagementSystem.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("NewspaperAdvertisementManagementSystem.Models.Advertisement", b =>
                {
                    b.Property<int>("AdvertisementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("AdminApproved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AdvPublishedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("AdvRegisteredDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AdvertisementDesc")
                        .HasColumnType("text");

                    b.Property<string>("AdvertisementSize")
                        .HasColumnType("text");

                    b.Property<string>("AdvertisementTitle")
                        .HasColumnType("text");

                    b.Property<string>("AdvertisementType")
                        .HasColumnType("text");

                    b.Property<bool>("Agree")
                        .HasColumnType("boolean");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Subscriber")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionPlan")
                        .HasColumnType("text");

                    b.HasKey("AdvertisementId");

                    b.HasIndex("ClientId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("NewspaperAdvertisementManagementSystem.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("NewspaperAdvertisementManagementSystem.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AdvertisementId")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentAmount")
                        .HasColumnType("integer");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text");

                    b.Property<string>("UpiId")
                        .HasColumnType("text");

                    b.HasKey("PaymentId");

                    b.HasIndex("AdvertisementId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("NewspaperAdvertisementManagementSystem.Models.Subscriber", b =>
                {
                    b.Property<int>("SubscriberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("text");

                    b.Property<string>("OfficeAddress")
                        .HasColumnType("text");

                    b.Property<string>("Popularity")
                        .HasColumnType("text");

                    b.Property<string>("Price")
                        .HasColumnType("text");

                    b.Property<string>("SubscriberDesc")
                        .HasColumnType("text");

                    b.HasKey("SubscriberId");

                    b.ToTable("Subscribers");
                });

            modelBuilder.Entity("NewspaperAdvertisementManagementSystem.Models.Advertisement", b =>
                {
                    b.HasOne("NewspaperAdvertisementManagementSystem.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewspaperAdvertisementManagementSystem.Models.Payment", b =>
                {
                    b.HasOne("NewspaperAdvertisementManagementSystem.Models.Advertisement", "Advertisement")
                        .WithMany()
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
