version: '3.1'

services:
  newspaperadvertisementmanagementsystem:
    image: anudeepgunukula/newspaperadvertisementmanagementsystem:dev
    container_name: NewspaperAdvertisementManagementSystem_1
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "NewspaperAdvertisementManagementSystem"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\anude\source\repos\AnudeepGunukula\NewspaperAdvertisementManagementSystem:/app
      - C:\Users\anude\source\repos\AnudeepGunukula\NewspaperAdvertisementManagementSystem:/src
      - C:\Users\anude\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\anude\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/netcoreapp3.1/NewspaperAdvertisementManagementSystem.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true